// packages/svelte/src/Renderer.svelte
<script module lang="ts">
  import type { Spec } from "@json-render/core";
  import ElementRenderer from "./ElementRenderer.svelte";
  import type { ComponentRegistry, ComponentRenderer } from "./renderer.js";

  /**
   * Props for the Renderer component
   */
  export interface RendererProps {
    /** The UI spec to render */
    spec: Spec | null;
    /** Component registry */
    registry: ComponentRegistry;
    /** Whether the spec is currently loading/streaming */
    loading?: boolean;
    /** Fallback component for unknown types */
    fallback?: ComponentRenderer;
  }
</script>

<script lang="ts">
  let { spec, registry, loading = false, fallback }: RendererProps = $props();

  let rootElement = $derived(spec?.root ? spec.elements[spec.root] : undefined);
</script>

{#if spec && rootElement}
  <ElementRenderer
    element={rootElement}
    {spec}
    {registry}
    {loading}
    {fallback} />
{/if}

// examples/ai-sdk/lib/render/renderer.tsx
"use client";

import { type ReactNode } from "react";
import {
  Renderer,
  type ComponentRenderer,
  type Spec,
  StateProvider,
  VisibilityProvider,
  ActionProvider,
} from "@json-render/react";

import { registry, Fallback } from "./registry";

// =============================================================================
// ExplorerRenderer
// =============================================================================

interface ExplorerRendererProps {
  spec: Spec | null;
  loading?: boolean;
}

const fallback: ComponentRenderer = ({ element }) => (
  <Fallback type={element.type} />
);

export function ExplorerRenderer({
  spec,
  loading,
}: ExplorerRendererProps): ReactNode {
  if (!spec) return null;

  return (
    <StateProvider initialState={spec.state ?? {}}>
      <VisibilityProvider>
        <ActionProvider>
          <Renderer
            spec={spec}
            registry={registry}
            fallback={fallback}
            loading={loading}
          />
        </ActionProvider>
      </VisibilityProvider>
    </StateProvider>
  );
}
