// examples/react-native/lib/render/renderer.tsx
import React, { type ReactNode } from "react";
import {
  Renderer,
  DataProvider,
  VisibilityProvider,
  ActionProvider,
  ValidationProvider,
  type Spec,
} from "@json-render/react-native";
import { registry } from "./registry";

// =============================================================================
// AppRenderer
// =============================================================================

interface AppRendererProps {
  spec: Spec | null;
  loading?: boolean;
}

export function AppRenderer({ spec, loading }: AppRendererProps): ReactNode {
  if (!spec) return null;

  return (
    <DataProvider>
      <VisibilityProvider>
        <ActionProvider handlers={{}}>
          <ValidationProvider>
            <Renderer spec={spec} registry={registry} loading={loading} />
          </ValidationProvider>
        </ActionProvider>
      </VisibilityProvider>
    </DataProvider>
  );
}

// examples/svelte-chat/src/lib/render/Renderer.svelte
<script lang="ts">
  import { Renderer, JsonUIProvider } from "@json-render/svelte";
  import type { Spec } from "@json-render/svelte";
  import { registry } from "./registry";

  interface Props {
    spec: Spec;
    loading?: boolean;
  }

  let { spec, loading = false }: Props = $props();
</script>

<JsonUIProvider initialState={spec.state}>
  <Renderer {spec} {registry} {loading} />
</JsonUIProvider>
